# Generated by Django 2.2.7 on 2020-03-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, null=None)),
                ('name_to_search', models.TextField(blank=True, null=None)),
                ('amount', models.TextField(blank=True, null=None)),
                ('price', models.TextField(blank=True, null=None)),
                ('year', models.TextField(blank=True, null=None)),
                ('category', models.TextField(blank=True, null=None)),
                ('category_to_search', models.TextField(blank=True, null=None)),
                ('is_hidden', models.BooleanField(blank=True, null=None)),
                ('photo_link', models.TextField(blank=True, null=None)),
                ('spot', models.TextField(blank=True, null=None)),
                ('sum', models.TextField(blank=True, null=None)),
                ('notes', models.TextField(blank=True, null=None)),
                ('index', models.IntegerField(blank=True, null=None, unique=True)),
                ('description', models.TextField(blank=True, default='defaultr dest test')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField()),
                ('last_edited', models.TextField()),
                ('index', models.IntegerField(blank=True, null=None, unique=True)),
            ],
        ),
    ]
