# Generated by Django 2.2.7 on 2019-11-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
