# Generated by Django 2.2.7 on 2019-11-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo_link',
            field=models.TextField(blank=True),
        ),
    ]
