# Generated by Django 2.2.7 on 2020-03-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempage',
            name='last_edited',
        ),
    ]
