# Generated by Django 2.2.7 on 2019-12-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sum',
            field=models.TextField(blank=True, null=None),
        ),
    ]
