# Generated by Django 2.2.7 on 2019-11-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='to_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='year',
            field=models.IntegerField(default=1000),
        ),
    ]
