# Generated by Django 2.2.7 on 2019-12-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20191222_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_to_search',
            field=models.TextField(blank=True, null=None),
        ),
    ]
