# Generated by Django 2.2.7 on 2019-11-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20191126_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='year',
            field=models.TextField(default=1000),
        ),
    ]
