# Generated by Django 2.2.7 on 2019-12-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_item_photo_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='to_show',
            new_name='is_hidden',
        ),
    ]
