# Generated by Django 2.2.7 on 2020-03-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_remove_itempage_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_edited',
            field=models.TextField(default='12.03.today'),
        ),
    ]
