# Generated by Django 2.2.7 on 2019-11-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20191126_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='to_show',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='year',
            field=models.TextField(blank=True, default=1000),
        ),
    ]
