# Generated by Django 2.2.7 on 2019-11-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20191127_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='year',
            field=models.TextField(blank=True),
        ),
    ]
