# Generated by Django 2.2.7 on 2019-11-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20191127_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.TextField(blank=True),
        ),
    ]
