# Generated by Django 2.2.7 on 2019-11-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.TextField(blank=True, null=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.TextField(blank=True, null=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(blank=True, null=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.TextField(blank=True, null=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='to_show',
            field=models.BooleanField(blank=True, null=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='year',
            field=models.TextField(blank=True, null=None),
        ),
    ]
